
version: 2.1

executors:
  jvm-executor:
    docker:
      - image: cimg/openjdk:17.0

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  run-checks-jvm:
    executor: jvm-executor

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Run checks on core
          command : ./gradlew :core:checkJvm

      - run:
          name: Run checks on engine
          command : ./gradlew :engine:checkJvm

      - run:
          name: Run checks on components
          command : ./gradlew :components:checkJvm

      - run:
          name: Run checks on imageio
          command : ./gradlew :imageio:checkJvm

#      - run:
#          name: Run checks on cli
#          command : ./gradlew :cli:checkJvm

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

      - store_test_results:
          path: ~/test-results

      - codecov/upload:
          file: core/build/reports/kover/report.xml
      - codecov/upload:
          file: engine/build/reports/kover/report.xml
      - codecov/upload:
          file: components/build/reports/kover/report.xml
      - codecov/upload:
          file: imageio/build/reports/kover/report.xml

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  ci:
    jobs:
      - run-checks-jvm